"""Schema creation and seeding for PostgreSQL."""

import hashlib

from db import connect
from config import PROFESSOR_LIST


def make_employee_id(professor_name: str, department: str) -> str:
    """The human-facing faculty ID, derived from name and department.

    Deterministic on purpose: the same professor keeps the same ID across
    re-seeds and across the MySQL migration. It is an identifier, not a secret
    — a login credential is the random qr_serial issued by an administrator.
    """
    raw = f"{professor_name.strip().lower()}|{department.strip().lower()}"
    return f"T-{int(hashlib.md5(raw.encode()).hexdigest(), 16) % 90000 + 10000}"


# password_hash is NOT NULL but nothing reads it any more — the password login
# routes are gone, and sign-in is by issued card or PIN. New rows get a value
# that cannot match any bcrypt check rather than a real hash of something.
_UNUSABLE_PASSWORD = "!disabled-no-password-login"

# Every table this app touches. `id` uses GENERATED BY DEFAULT AS IDENTITY
# rather than plain SERIAL so the MySQL migration can insert its original
# primary keys verbatim and keep foreign keys lined up.
SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS professors (
        id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        VARCHAR(255) NOT NULL,
        department  VARCHAR(255) NOT NULL,
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_prof UNIQUE (name, department)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS students (
        id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id    VARCHAR(50) UNIQUE NOT NULL,
        full_name     VARCHAR(255) NOT NULL,
        course        VARCHAR(255),
        year_level    VARCHAR(20),
        department    VARCHAR(255),
        qr_code_path  VARCHAR(500),
        pin_hash      VARCHAR(255),
        photo         TEXT,
        created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS teacher_accounts (
        id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id    VARCHAR(50) UNIQUE NOT NULL,
        professor_name VARCHAR(255) NOT NULL,
        department     VARCHAR(255) NOT NULL,
        password_hash  VARCHAR(255) NOT NULL,
        qr_code_path   VARCHAR(500),
        pin_hash       VARCHAR(255),
        photo          TEXT,
        created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS teacher_logs (
        id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        professor_name  VARCHAR(255),
        department      VARCHAR(255),
        action_type     VARCHAR(100),
        schedule_am     TIMESTAMP,
        schedule_pm     TIMESTAMP,
        manual_status   VARCHAR(100),
        manual          BOOLEAN DEFAULT FALSE,
        weekly_schedule JSONB,
        log_time        TIMESTAMP,
        created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS consultation_requests (
        id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id         VARCHAR(50),
        student_name       VARCHAR(255),
        course             VARCHAR(255),
        professor_name     VARCHAR(255),
        professor_id       INT,
        purpose            TEXT,
        category           VARCHAR(100),
        status             VARCHAR(20) DEFAULT 'pending',
        request_time       TIMESTAMP,
        department         VARCHAR(255),
        appointment_date   DATE,
        appointment_time   VARCHAR(20),
        appointment_notes  TEXT,
        appointment_set_at TIMESTAMP,
        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    # Written to by the biometric enrolment route. MySQL never had this table
    # declared anywhere, so enrolment failed there; it is created properly here.
    # Who did what, and when. Written by security.record_audit(). Without this
    # an account takeover leaves no trace at all — there was nothing to review.
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        actor_role  VARCHAR(20),
        actor_id    VARCHAR(100),
        actor_name  VARCHAR(255),
        action      VARCHAR(100) NOT NULL,
        target      VARCHAR(255),
        detail      TEXT,
        ip          VARCHAR(64),
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS biometrics (
        id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id  INT UNIQUE REFERENCES students(id) ON DELETE CASCADE,
        face_file   VARCHAR(255),
        eye_file    VARCHAR(255),
        enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]

# Indexes for the lookups this app does on every dashboard poll.
INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_cr_professor    ON consultation_requests (professor_name)",
    "CREATE INDEX IF NOT EXISTS idx_cr_student      ON consultation_requests (student_id)",
    "CREATE INDEX IF NOT EXISTS idx_cr_status       ON consultation_requests (status)",
    "CREATE INDEX IF NOT EXISTS idx_cr_created      ON consultation_requests (created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_tl_action       ON teacher_logs (action_type, professor_name, department)",
    "CREATE INDEX IF NOT EXISTS idx_audit_created   ON audit_log (created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_audit_action    ON audit_log (action)",
    # QR logins look an account up by serial on every scan.
    "CREATE UNIQUE INDEX IF NOT EXISTS idx_ta_qr_serial ON teacher_accounts (qr_serial) WHERE qr_serial IS NOT NULL",
    # "Who is on right now" scans by recency, and the admin dashboard asks every
    # half minute while it is open.
    "CREATE INDEX IF NOT EXISTS idx_students_seen  ON students (last_seen DESC)",
]

# Columns added after the original release. Older databases (and the MySQL one
# being migrated from) may not have them yet.
LATE_COLUMNS = [
    ("students",              "pin_hash",           "VARCHAR(255)"),
    ("students",              "photo",              "TEXT"),
    ("teacher_accounts",      "photo",              "TEXT"),
    ("teacher_accounts",      "pin_hash",           "VARCHAR(255)"),
    ("consultation_requests", "appointment_date",   "DATE"),
    ("consultation_requests", "appointment_time",   "VARCHAR(20)"),
    ("consultation_requests", "appointment_notes",  "TEXT"),
    ("consultation_requests", "appointment_set_at", "TIMESTAMP"),
    # Credential + session columns. qr_serial is the random value a faculty QR
    # card actually encodes; it starts NULL, and a NULL serial can never match a
    # scan, so no account has a working card until an admin issues one.
    ("teacher_accounts",      "qr_serial",          "VARCHAR(64)"),
    ("teacher_accounts",      "qr_issued_at",       "TIMESTAMP"),
    ("teacher_accounts",      "last_login",         "TIMESTAMP"),
    ("teacher_accounts",      "active",             "BOOLEAN DEFAULT TRUE"),
    # Removal is a tombstone, not a DELETE. The roster in config is re-seeded on
    # every boot, so a deleted row for a listed professor would simply come back
    # on the next restart; a marked row is skipped by the seeder's ON CONFLICT
    # and stays gone. It also keeps the reason attached to the account itself,
    # not only to the audit line.
    # How many consultations this teacher will take in a day. 0 means "no limit
    # of my own" — the per-day figure in the weekly schedule is used instead.
    ("teacher_accounts",      "daily_limit",        "INT DEFAULT 0"),
    # Identity beyond the name. Two professors can share a name; an email and a
    # school-issued staff number cannot be shared, and the position is what an
    # administrator recognises someone by on a roster of forty.
    ("teacher_accounts",      "email",              "VARCHAR(255)"),
    ("teacher_accounts",      "position",           "VARCHAR(120)"),
    ("teacher_accounts",      "staff_no",           "VARCHAR(60)"),
    ("teacher_accounts",      "removed_at",         "TIMESTAMP"),
    ("teacher_accounts",      "removed_reason",     "TEXT"),
    ("students",              "last_login",         "TIMESTAMP"),
    # Anyone could register as a student and start filing requests at faculty:
    # the form asked for a name and an ID, and neither was checked against
    # anything. An account is now unverified until an administrator confirms the
    # person is enrolled; unverified accounts can look, not book.
    ("students",              "email",              "VARCHAR(255)"),
    ("students",              "verified",           "BOOLEAN DEFAULT FALSE"),
    ("students",              "verified_at",        "TIMESTAMP"),
    ("students",              "verified_by",        "VARCHAR(120)"),
    # Presence. last_login only ever answered "did they ever come back?"; these
    # answer "is anyone using this right now, and for how long?", which is the
    # question an administrator watching a consultation period actually has.
    # Written in Manila time by security.touch_presence, at most once a minute
    # per student.
    ("students",              "last_seen",          "TIMESTAMP"),
    ("students",              "session_started_at", "TIMESTAMP"),
]

# The status column used to be a MySQL ENUM. It is a plain VARCHAR here, with a
# CHECK constraint doing the same job.
STATUS_VALUES = ("pending", "done", "declined", "archived")


def init_db():
    """Create every table, index and constraint if missing, then seed professors."""
    conn = connect()
    cur = conn.cursor()
    try:
        for statement in SCHEMA:
            cur.execute(statement)

        _add_missing_columns(cur)

        for statement in INDEXES:
            cur.execute(statement)

        _ensure_status_check(cur)

        # Seed the professor roster from config.
        for dept, profs in PROFESSOR_LIST.items():
            for name in profs:
                cur.execute(
                    "INSERT INTO professors (name, department) VALUES (%s, %s) "
                    "ON CONFLICT (name, department) DO NOTHING",
                    (name, dept),
                )

        created = _seed_teacher_accounts(cur)
        cleared = _clear_removed_teacher_photos(cur)
        print(
            "[DB] Tables created and professors seeded"
            + (f"; {created} faculty account(s) created." if created else ".")
            + (f" Cleared {cleared} photo(s) from removed accounts." if cleared else "")
        )
    finally:
        try:
            cur.close()
        except Exception:
            pass
        conn.close()


def _clear_removed_teacher_photos(cur):
    """Drop photos left behind by teachers removed before removal cleared them.

    Removing a teacher is a tombstone rather than a DELETE, and for most of this
    project's life it kept the photo — the row's one heavy column, base64 in
    TEXT at 80-95KB. Clearing it on removal only helps accounts removed after
    that change; the ones already in the table keep theirs until something goes
    and gets them, and no vacuum will: to Postgres a photo on a tombstoned row
    is live data, faithfully preserved.

    So this is that something. It is also the more pressing half of the reason:
    a former staff member's face sitting in a database indefinitely is a problem
    on its own terms, quite apart from the bytes.

    Idempotent and self-extinguishing — once run it matches nothing, and on a
    table of a few dozen rows the check costs nothing to repeat on every boot.
    """
    cur.execute(
        "UPDATE teacher_accounts SET photo=NULL "
        "WHERE removed_at IS NOT NULL AND photo IS NOT NULL"
    )
    return cur.rowcount or 0


def _seed_teacher_accounts(cur):
    """Give every professor in the roster a faculty account.

    Accounts used to be created lazily, the first time a professor used the
    public quick-login endpoint. That endpoint handed out login credentials to
    anyone who asked and has been removed, which left the roster and the
    accounts table disconnected: the professors were listed everywhere, but an
    administrator had nothing to issue a card against.

    An account here carries no way in on its own — qr_serial and pin_hash are
    both NULL until an administrator issues a card. Idempotent, so professors
    added to PROFESSOR_LIST later are picked up on the next boot.
    """
    created = 0
    for dept, profs in PROFESSOR_LIST.items():
        for name in profs:
            cur.execute(
                "INSERT INTO teacher_accounts "
                "(employee_id, professor_name, department, password_hash) "
                "VALUES (%s, %s, %s, %s) ON CONFLICT (employee_id) DO NOTHING",
                (make_employee_id(name, dept), name, dept, _UNUSABLE_PASSWORD),
            )
            created += cur.rowcount or 0
    return created


def _add_missing_columns(cur):
    tables = sorted({t for t, _, _ in LATE_COLUMNS})
    cur.execute(
        "SELECT table_name, column_name FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = ANY(%s)",
        (tables,),
    )
    existing = {(r[0], r[1]) for r in cur.fetchall()}
    for table, column, definition in LATE_COLUMNS:
        if (table, column) not in existing:
            cur.execute(f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}')
            print(f"[DB] Added column {table}.{column}")


def _ensure_status_check(cur):
    """Replace the old MySQL ENUM with an equivalent CHECK constraint."""
    values = ", ".join(f"'{v}'" for v in STATUS_VALUES)
    cur.execute(
        "SELECT 1 FROM pg_constraint WHERE conname = 'ck_cr_status' "
        "AND conrelid = 'consultation_requests'::regclass"
    )
    if cur.fetchone():
        return
    try:
        cur.execute(
            f"ALTER TABLE consultation_requests ADD CONSTRAINT ck_cr_status "
            f"CHECK (status IN ({values}))"
        )
    except Exception as exc:
        # Existing rows carrying some other status shouldn't block startup.
        print(f"[DB] Skipped status CHECK constraint: {exc}")
