"""Schema creation and seeding for PostgreSQL."""

from db import connect
from config import PROFESSOR_LIST

# Every table this app touches. `id` uses GENERATED BY DEFAULT AS IDENTITY
# rather than plain SERIAL so the MySQL migration can insert its original
# primary keys verbatim and keep foreign keys lined up.
SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS professors (
        id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name        VARCHAR(255) NOT NULL,
        department  VARCHAR(255) NOT NULL,
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT uq_prof UNIQUE (name, department)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS students (
        id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id    VARCHAR(50) UNIQUE NOT NULL,
        full_name     VARCHAR(255) NOT NULL,
        course        VARCHAR(255),
        year_level    VARCHAR(20),
        department    VARCHAR(255),
        qr_code_path  VARCHAR(500),
        pin_hash      VARCHAR(255),
        photo         TEXT,
        created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS teacher_accounts (
        id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id    VARCHAR(50) UNIQUE NOT NULL,
        professor_name VARCHAR(255) NOT NULL,
        department     VARCHAR(255) NOT NULL,
        password_hash  VARCHAR(255) NOT NULL,
        qr_code_path   VARCHAR(500),
        pin_hash       VARCHAR(255),
        photo          TEXT,
        created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS teacher_logs (
        id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        professor_name  VARCHAR(255),
        department      VARCHAR(255),
        action_type     VARCHAR(100),
        schedule_am     TIMESTAMP,
        schedule_pm     TIMESTAMP,
        manual_status   VARCHAR(100),
        manual          BOOLEAN DEFAULT FALSE,
        weekly_schedule JSONB,
        log_time        TIMESTAMP,
        created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS consultation_requests (
        id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id         VARCHAR(50),
        student_name       VARCHAR(255),
        course             VARCHAR(255),
        professor_name     VARCHAR(255),
        professor_id       INT,
        purpose            TEXT,
        category           VARCHAR(100),
        status             VARCHAR(20) DEFAULT 'pending',
        request_time       TIMESTAMP,
        department         VARCHAR(255),
        appointment_date   DATE,
        appointment_time   VARCHAR(20),
        appointment_notes  TEXT,
        appointment_set_at TIMESTAMP,
        created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
    # Written to by the biometric enrolment route. MySQL never had this table
    # declared anywhere, so enrolment failed there; it is created properly here.
    """
    CREATE TABLE IF NOT EXISTS biometrics (
        id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        student_id  INT UNIQUE REFERENCES students(id) ON DELETE CASCADE,
        face_file   VARCHAR(255),
        eye_file    VARCHAR(255),
        enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    """,
]

# Indexes for the lookups this app does on every dashboard poll.
INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_cr_professor    ON consultation_requests (professor_name)",
    "CREATE INDEX IF NOT EXISTS idx_cr_student      ON consultation_requests (student_id)",
    "CREATE INDEX IF NOT EXISTS idx_cr_status       ON consultation_requests (status)",
    "CREATE INDEX IF NOT EXISTS idx_cr_created      ON consultation_requests (created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_tl_action       ON teacher_logs (action_type, professor_name, department)",
]

# Columns added after the original release. Older databases (and the MySQL one
# being migrated from) may not have them yet.
LATE_COLUMNS = [
    ("students",              "pin_hash",           "VARCHAR(255)"),
    ("students",              "photo",              "TEXT"),
    ("teacher_accounts",      "photo",              "TEXT"),
    ("teacher_accounts",      "pin_hash",           "VARCHAR(255)"),
    ("consultation_requests", "appointment_date",   "DATE"),
    ("consultation_requests", "appointment_time",   "VARCHAR(20)"),
    ("consultation_requests", "appointment_notes",  "TEXT"),
    ("consultation_requests", "appointment_set_at", "TIMESTAMP"),
]

# The status column used to be a MySQL ENUM. It is a plain VARCHAR here, with a
# CHECK constraint doing the same job.
STATUS_VALUES = ("pending", "done", "declined", "archived")


def init_db():
    """Create every table, index and constraint if missing, then seed professors."""
    conn = connect()
    cur = conn.cursor()
    try:
        for statement in SCHEMA:
            cur.execute(statement)

        _add_missing_columns(cur)

        for statement in INDEXES:
            cur.execute(statement)

        _ensure_status_check(cur)

        # Seed the professor roster from config.
        for dept, profs in PROFESSOR_LIST.items():
            for name in profs:
                cur.execute(
                    "INSERT INTO professors (name, department) VALUES (%s, %s) "
                    "ON CONFLICT (name, department) DO NOTHING",
                    (name, dept),
                )
        print("[DB] Tables created and professors seeded.")
    finally:
        try:
            cur.close()
        except Exception:
            pass
        conn.close()


def _add_missing_columns(cur):
    tables = sorted({t for t, _, _ in LATE_COLUMNS})
    cur.execute(
        "SELECT table_name, column_name FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = ANY(%s)",
        (tables,),
    )
    existing = {(r[0], r[1]) for r in cur.fetchall()}
    for table, column, definition in LATE_COLUMNS:
        if (table, column) not in existing:
            cur.execute(f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {definition}')
            print(f"[DB] Added column {table}.{column}")


def _ensure_status_check(cur):
    """Replace the old MySQL ENUM with an equivalent CHECK constraint."""
    values = ", ".join(f"'{v}'" for v in STATUS_VALUES)
    cur.execute(
        "SELECT 1 FROM pg_constraint WHERE conname = 'ck_cr_status' "
        "AND conrelid = 'consultation_requests'::regclass"
    )
    if cur.fetchone():
        return
    try:
        cur.execute(
            f"ALTER TABLE consultation_requests ADD CONSTRAINT ck_cr_status "
            f"CHECK (status IN ({values}))"
        )
    except Exception as exc:
        # Existing rows carrying some other status shouldn't block startup.
        print(f"[DB] Skipped status CHECK constraint: {exc}")
